services:
  app-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      app-db:
        condition: service_healthy

  app-db:
    image: mysql:8.4
    container_name: app-db
    environment:
      MYSQL_ROOT_PASSWORD: 12341234
      MYSQL_DATABASE: app-db
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "33061:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 3s
      retries: 10
